-- Fotos del equipo asociadas a órdenes de servicio (reparaciones).

CREATE TABLE IF NOT EXISTS public.reparacion_fotos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repara_id bigint NOT NULL REFERENCES public.reparaciones (id) ON DELETE CASCADE,
  storage_path text NOT NULL UNIQUE,
  nombre_archivo text,
  mime text,
  bytes bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS reparacion_fotos_repara_id_idx
  ON public.reparacion_fotos (repara_id);

COMMENT ON TABLE public.reparacion_fotos IS
  'Metadatos de fotos del equipo ligadas a una orden de servicio.';

ALTER TABLE public.reparacion_fotos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS staff_authenticated_all ON public.reparacion_fotos;
CREATE POLICY staff_authenticated_all ON public.reparacion_fotos
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

-- Bucket para fotos de orden (sin tope de tamaño; MIME de imagen comunes).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'orden-fotos',
  'orden-fotos',
  true,
  NULL,
  ARRAY[
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/webp',
    'image/heic',
    'image/heif',
    'image/gif'
  ]::text[]
)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS orden_fotos_select_auth ON storage.objects;
CREATE POLICY orden_fotos_select_auth
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'orden-fotos');

DROP POLICY IF EXISTS orden_fotos_insert_auth ON storage.objects;
CREATE POLICY orden_fotos_insert_auth
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'orden-fotos');

DROP POLICY IF EXISTS orden_fotos_update_auth ON storage.objects;
CREATE POLICY orden_fotos_update_auth
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'orden-fotos')
WITH CHECK (bucket_id = 'orden-fotos');

DROP POLICY IF EXISTS orden_fotos_delete_auth ON storage.objects;
CREATE POLICY orden_fotos_delete_auth
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'orden-fotos');

-- Cascada explícita de fotos al eliminar la orden completa.
CREATE OR REPLACE FUNCTION public.eliminar_reparacion_completa(p_repara_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cuenta_ids bigint[];
BEGIN
  IF NOT public.puede_eliminar_actual() THEN
    RAISE EXCEPTION 'No autorizado para eliminar órdenes'
      USING ERRCODE = '42501';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.reparaciones r WHERE r.id = p_repara_id) THEN
    RAISE EXCEPTION 'No se encontró la orden %', p_repara_id
      USING ERRCODE = 'P0002';
  END IF;

  SELECT array_agg(c.id)
  INTO v_cuenta_ids
  FROM public.cuentas c
  WHERE c.repara_id = p_repara_id;

  IF v_cuenta_ids IS NOT NULL THEN
    DELETE FROM public.pagosclientes WHERE cuenta_id = ANY (v_cuenta_ids);
    DELETE FROM public.cuentamov WHERE cuenta_id = ANY (v_cuenta_ids);
  END IF;

  DELETE FROM public.reparamov WHERE repara_id = p_repara_id;
  DELETE FROM public.reparacion_fotos WHERE repara_id = p_repara_id;
  DELETE FROM public.cuentas WHERE repara_id = p_repara_id;
  DELETE FROM public.reparaciones WHERE id = p_repara_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No se pudo eliminar la orden %', p_repara_id
      USING ERRCODE = 'P0002';
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.eliminar_reparacion_completa(bigint) TO authenticated;
