-- Adjuntos de orden: permitir cualquier tipo de archivo (png, jpg, pdf, etc.).

-- Asegurar tabla (por si la migración anterior no se aplicó).
CREATE TABLE IF NOT EXISTS public.reparacion_fotos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repara_id bigint NOT NULL REFERENCES public.reparaciones (id) ON DELETE CASCADE,
  storage_path text NOT NULL UNIQUE,
  nombre_archivo text,
  mime text,
  bytes bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS reparacion_fotos_repara_id_idx
  ON public.reparacion_fotos (repara_id);

ALTER TABLE public.reparacion_fotos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS staff_authenticated_all ON public.reparacion_fotos;
CREATE POLICY staff_authenticated_all ON public.reparacion_fotos
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

-- Bucket sin restricción de MIME ni tamaño práctico.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'orden-fotos',
  'orden-fotos',
  true,
  NULL,
  NULL
)
ON CONFLICT (id) DO UPDATE
SET public = true,
    file_size_limit = NULL,
    allowed_mime_types = NULL;

-- Lectura pública (URLs del navegador en <img> / abrir PDF sin token).
DROP POLICY IF EXISTS orden_fotos_select_auth ON storage.objects;
DROP POLICY IF EXISTS orden_fotos_select_public ON storage.objects;
CREATE POLICY orden_fotos_select_public
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'orden-fotos');

DROP POLICY IF EXISTS orden_fotos_insert_auth ON storage.objects;
CREATE POLICY orden_fotos_insert_auth
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'orden-fotos');

DROP POLICY IF EXISTS orden_fotos_update_auth ON storage.objects;
CREATE POLICY orden_fotos_update_auth
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'orden-fotos')
WITH CHECK (bucket_id = 'orden-fotos');

DROP POLICY IF EXISTS orden_fotos_delete_auth ON storage.objects;
CREATE POLICY orden_fotos_delete_auth
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'orden-fotos');
