-- Cotizaciones a clientes (líneas en cotizacionmov; sin pagos ni inventario hasta convertir a cuenta).

CREATE TABLE IF NOT EXISTS public.cotizaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id bigint NOT NULL REFERENCES public.clientes (id) ON DELETE CASCADE,
  total numeric(12, 2) NOT NULL DEFAULT 0,
  estatus text NOT NULL DEFAULT 'BORRADOR',
  notas text,
  validez_hasta date,
  cuenta_id bigint REFERENCES public.cuentas (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cotizacionmov (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id bigint NOT NULL REFERENCES public.cotizaciones (id) ON DELETE CASCADE,
  producto_id bigint,
  cantidad numeric(12, 2) NOT NULL DEFAULT 1,
  descripcion text NOT NULL DEFAULT '',
  costo numeric(12, 2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS cotizaciones_cliente_id_idx ON public.cotizaciones (cliente_id);
CREATE INDEX IF NOT EXISTS cotizacionmov_cotizacion_id_idx ON public.cotizacionmov (cotizacion_id);

ALTER TABLE public.cotizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cotizacionmov ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS staff_authenticated_all ON public.cotizaciones;
CREATE POLICY staff_authenticated_all ON public.cotizaciones
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS staff_authenticated_all ON public.cotizacionmov;
CREATE POLICY staff_authenticated_all ON public.cotizacionmov
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);
